Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/nfs/home/ernstd/miniconda3/envs/transformer/lib/python3.12/site-packages/transformers/models/llava/configuration_llava.py:103: FutureWarning: The `vocab_size` argument is deprecated and will be removed in v4.42, since it can be inferred from the `text_config`. Passing this argument has no effect
  warnings.warn(
You are attempting to use Flash Attention 2.0 without specifying a torch dtype. This might lead to unexpected behaviour
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:25<00:51, 25.99s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:53<00:27, 27.09s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:23<00:00, 55.50s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:23<00:00, 47.72s/it]
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/mantis/mantis.py", line 242, in <module>
    run(args, answerFile)
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/mantis/mantis.py", line 220, in run
    questions.append(json.loads(line))
                     ^^^^^^^^^^^^^^^^
  File "/nfs/home/ernstd/miniconda3/envs/transformer/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/ernstd/miniconda3/envs/transformer/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/ernstd/miniconda3/envs/transformer/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 93 (char 92)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Python version is above 3.10, patching the collections module.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [01:59<03:58, 119.07s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [02:00<00:49, 49.71s/it] Loading checkpoint shards: 100%|██████████| 3/3 [03:33<00:00, 69.51s/it]Loading checkpoint shards: 100%|██████████| 3/3 [03:33<00:00, 71.10s/it]
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/DeepSeek/deepseek.py", line 180, in <module>
    run(args, answerFile)
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/DeepSeek/deepseek.py", line 148, in run
    questions.append(json.loads(line))
                     ^^^^^^^^^^^^^^^^
  File "/nfs/home/ernstd/miniconda3/envs/transformer/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/ernstd/miniconda3/envs/transformer/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/home/ernstd/miniconda3/envs/transformer/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 93 (char 92)
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./experiments/02_with_comparative_images/22_multi_input_models/221_entity_verification_1x1/scripts/tamperednews/printResultTable.py", line 65, in <module>
    printResults(args)
  File "/nfs/home/ernstd/masterthesis_scripts/./experiments/02_with_comparative_images/22_multi_input_models/221_entity_verification_1x1/scripts/tamperednews/printResultTable.py", line 49, in printResults
    getValue(resultsVLM[args.models[2]], entityType), 
                        ~~~~~~~~~~~^^^
IndexError: list index out of range
