python: can't open file '/nfs/home/ernstd/masterthesis_scripts/./experiments/4_multi_image_entity_verification/scripts/tamperednews/prepare_questions.py': [Errno 2] No such file or directory
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:01<00:01,  1.48s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.13s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.18s/it]
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/blip2.py", line 128, in <module>
    run(args, answerFile)
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/blip2.py", line 104, in run
    with open(args.question_file, encoding="utf-8", mode='r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './experiments/4_multi_image_entity_verification/_questions/questions_tamperednews.jsonl'
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:01<00:04,  1.45s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:02<00:02,  1.43s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:04<00:01,  1.38s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.04it/s]Loading checkpoint shards: 100%|██████████| 4/4 [00:04<00:00,  1.13s/it]
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/instructblip.py", line 132, in <module>
    run(args, answerFile)
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/instructblip.py", line 108, in run
    with open(args.question_file, encoding="utf-8", mode='r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './experiments/4_multi_image_entity_verification/_questions/questions_tamperednews.jsonl'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:01<00:03,  1.54s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:02<00:01,  1.14s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:03<00:00,  1.08it/s]Loading checkpoint shards: 100%|██████████| 3/3 [00:03<00:00,  1.02s/it]
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/llava.py", line 135, in <module>
    run(args, answerFile)
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/llava.py", line 110, in run
    with open(args.question_file, encoding="utf-8", mode='r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './experiments/4_multi_image_entity_verification/_questions/questions_tamperednews.jsonl'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]Loading checkpoint shards:  17%|█▋        | 1/6 [00:01<00:07,  1.44s/it]Loading checkpoint shards:  33%|███▎      | 2/6 [00:02<00:04,  1.22s/it]Loading checkpoint shards:  50%|█████     | 3/6 [00:03<00:03,  1.15s/it]Loading checkpoint shards:  67%|██████▋   | 4/6 [00:06<00:03,  1.99s/it]Loading checkpoint shards:  83%|████████▎ | 5/6 [00:08<00:01,  1.73s/it]Loading checkpoint shards: 100%|██████████| 6/6 [00:08<00:00,  1.33s/it]Loading checkpoint shards: 100%|██████████| 6/6 [00:08<00:00,  1.44s/it]
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/llava-4bit.py", line 140, in <module>
    run(args, answerFile)
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/llava-4bit.py", line 113, in run
    with open(args.question_file, encoding="utf-8", mode='r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './experiments/4_multi_image_entity_verification/_questions/questions_tamperednews.jsonl'
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:01<00:04,  1.57s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:02<00:02,  1.10s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:03<00:00,  1.06it/s]Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.29it/s]Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.11it/s]
Some weights of the model checkpoint at ./models/llava-v1.6-mistral-7b-hf/ were not used when initializing LlavaForConditionalGeneration: ['image_newline']
- This IS expected if you are initializing LlavaForConditionalGeneration from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlavaForConditionalGeneration from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/llava.py", line 135, in <module>
    run(args, answerFile)
  File "/nfs/home/ernstd/masterthesis_scripts/./model_scripts/llava.py", line 110, in run
    with open(args.question_file, encoding="utf-8", mode='r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './experiments/4_multi_image_entity_verification/_questions/questions_tamperednews.jsonl'
python: can't open file '/nfs/home/ernstd/masterthesis_scripts/./experiments/4_multi_image_entity_verification/scripts/tamperednews/analyze_answers.py': [Errno 2] No such file or directory
python: can't open file '/nfs/home/ernstd/masterthesis_scripts/./4_multi_image_entity_verification/scripts/tamperednews/printResultTable.py': [Errno 2] No such file or directory
